FROM python:3.11-slim
WORKDIR /app
COPY . .
ENV PYTHONPATH=/app
ENV GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
RUN pip install --no-cache-dir -r api/requirements.txt
EXPOSE 8000
CMD ["uvicorn","api.inference_main:app","--host","0.0.0.0","--port","8000"]
