FROM python:3.11-slim

WORKDIR /app

COPY AI_backend/api/requirements.txt ./AI_backend/api/requirements.txt

RUN pip install --no-cache-dir -r AI_backend/api/requirements.txt

COPY . .

ENV PYTHONPATH=/app
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/AI_backend/serviceAccountKey.json

EXPOSE 8000

CMD ["uvicorn", "AI_backend.api.inference_main:app", "--host", "0.0.0.0", "--port", "8000"]
